### ISSUE TITLE
Misleading plugins pull message

### ISSUE THREAD

**Issue by sewnie** [erf/vis-plug#38]
https://github.com/erf/vis-plug/blob/master/init.lua#L309

When `:plug-update` is called, and it finishes, it always responds back with `$n plugin(s) updated`, which signifies that these updates were updated successfully, but it always prints this, regardless whether or not the plugin is _actually_ updated. It should check if the plugin had recieved an update and print accordingly.

**Comment by erf** [comment]
Previously i did a `git pull` on all plugins, even if they were outdated or not. This was partially because it was a simple solution, but also because doing a check if things needed update would require additional checks and is maybe more costly in time than just do a git pull on all repos. However this is now fixed in e2d114982d3c9eda1e5376760eea2b59a58bf25e . Where i check latest and compare with the local hash before fetching those which needs update. I also now check if repos are outdated in parallell and use the same method for `update` .

**Comment by sewnie** [comment]
I feel like this solution adds too much. Instead of locally storing plugin information, why not simply check for the output information omitted by `git pull`?

**Comment by erf** [comment]
You're right. I've made some updates. Also don't write to disk now.

**Comment by sewnie** [comment]
Thanks!
